const FOLDER_NAME = 'logs';
const FILE_NAME_URL_PAGE_PROVINCES = 'urlPageProvinces.json';
const FILE_NAME_URL_DETAILS_WAREHOUSE = 'urlDetailsWarehouse.json';
const FILE_NAME_OUTPUT = 'output.json';
const TIMEOUT_REQUEST_URL_WAREHOUSE = 500; // TIMEOUT = 0.5 (s)

export { FOLDER_NAME, FILE_NAME_URL_PAGE_PROVINCES, FILE_NAME_URL_DETAILS_WAREHOUSE, FILE_NAME_OUTPUT, TIMEOUT_REQUEST_URL_WAREHOUSE };
