const FOLDER_FILE_JSON = 'logs';
const FILE_PROVINCES = 'provinces.json';
const FILE_URL_PROVINCES = 'urlProvinces.json';
const FILE_URL_WAREHOUSE = 'urlWarehouse.json';
const FILE_DATA_WAREHOUSE = 'dataWarehouse.json';
const TIMEOUT_BETWEEN_REQUEST = 0; // TIMEOUT = 0.5 (s)F
const FILE_STATUS_CRAWL = 'statusCrawl.txt';

export { FOLDER_FILE_JSON, FILE_PROVINCES, FILE_URL_PROVINCES, FILE_URL_WAREHOUSE, FILE_DATA_WAREHOUSE, TIMEOUT_BETWEEN_REQUEST, FILE_STATUS_CRAWL };
